### ISSUE TITLE
Can you add functionality to use ssh port from config file?

### ISSUE THREAD

**Issue by denisgolius** [mxssl/cmd-runner#1]
https://github.com/mxssl/cmd-runner/blob/master/cmd/start.go#L131

Because I use different ports and I want to add ports into config.toml

**Comment by mxssl** [comment]
Hi Denis,

Thank you for your interest in my project.

I implemented the feature that you asked. New configuration file:
https://github.com/mxssl/cmd-runner/blob/master/config.toml

Please download new binary:

[Linux](https://github.com/mxssl/cmd-runner/releases/download/0.0.4/cmd-runner-linux-amd64)

[MacOS](https://github.com/mxssl/cmd-runner/releases/download/0.0.4/cmd-runner-darwin-amd64)
